name: cherry_toast
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/icons/ic_error.png
    - assets/icons/ic_info.png
    - assets/icons/ic_warning.png
    - assets/icons/ic_success.png
  # fonts:
  #   - family: CherryToastIcons
  #     fonts:
  #       - asset: assets/fonts/CherryToastIcons.ttf
