name: cherry_toast
description: A new way to display toasts in flutter with elegant design and animations
version: 1.0.0
homepage: https://github.com/koukibadr/Cherry-Toast

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/icons/ic_error.png
    - assets/icons/ic_info.png
    - assets/icons/ic_warning.png
    - assets/icons/ic_success.png
    - assets/icons/ic_close.png
